### ISSUE TITLE
Bug ((

### ISSUE THREAD

**Issue by airat9000** [LovelySanta/FactorioMod-MoreScience-BobAngelsExtension#2]
Bug not work
![2018-08-02_20-38-46](https://user-images.githubusercontent.com/19721445/43600866-793e5f56-9694-11e8-8452-18dd51152957.png)
change recipe
2 bug
![2018-08-02_20-49-35](https://user-images.githubusercontent.com/19721445/43601361-a4bf51fc-9695-11e8-9fa2-7cbdb1e8ea29.png)

**Comment by LovelySanta** [comment]
I have no compatibility with the py or darkstar mods yet. I might add this support, but not in the near feature at least...

EDIT: at first sight it doesn't even show that its my mod, becose otherwise it should tell to disable MoreScience too... In the first bug it only disables darkstar and angelsrefinning and on the second one only pycoal... I would need to investigate this further to be sure anyway.

Kind regards,
lovely_santa

**Comment by airat9000** [comment]
an pyadon mods not normal works

**Comment by LovelySanta** [comment]
I don't know if angel has py support build in... I don't have that at least... (yet)

Kind regards,
lovely_santa

**Comment by LovelySanta** [comment]
I'll close this topic since this isn't specific part of the bobs angels extension. For future progress, look over at LovelySanta/FactorioMod-MoreScience#2 .

Kind regards,
lovely_santa
